package org.sunside.frame.ibatis.repository.model;

import java.util.Date;

public class SysUser {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.user_name
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String userName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.password
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.chinese_name
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String chineseName;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.dept_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Long deptId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.post_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Long postId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.sex
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String sex;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.age
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Integer age;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.zip_code
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String zipCode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.email
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.phone_no
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String phoneNo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.address
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.note
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String note;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.version_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Long versionId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.reccreator
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String reccreator;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.reccreate_time
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Date reccreateTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.recrevisor
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String recrevisor;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.recrevise_time
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private Date recreviseTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column sys_user.archive_flag
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private String archiveFlag;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.id
	 * @return  the value of sys_user.id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.id
	 * @param id  the value for sys_user.id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.user_name
	 * @return  the value of sys_user.user_name
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.user_name
	 * @param userName  the value for sys_user.user_name
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.chinese_name
	 * @return  the value of sys_user.chinese_name
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getChineseName() {
		return chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.chinese_name
	 * @param chineseName  the value for sys_user.chinese_name
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setChineseName(String chineseName) {
		this.chineseName = chineseName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.dept_id
	 * @return  the value of sys_user.dept_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Long getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.dept_id
	 * @param deptId  the value for sys_user.dept_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.post_id
	 * @return  the value of sys_user.post_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Long getPostId() {
		return postId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.post_id
	 * @param postId  the value for sys_user.post_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setPostId(Long postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.sex
	 * @return  the value of sys_user.sex
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.sex
	 * @param sex  the value for sys_user.sex
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.age
	 * @return  the value of sys_user.age
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.age
	 * @param age  the value for sys_user.age
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.zip_code
	 * @return  the value of sys_user.zip_code
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.zip_code
	 * @param zipCode  the value for sys_user.zip_code
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.email
	 * @return  the value of sys_user.email
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.email
	 * @param email  the value for sys_user.email
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.phone_no
	 * @return  the value of sys_user.phone_no
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getPhoneNo() {
		return phoneNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.phone_no
	 * @param phoneNo  the value for sys_user.phone_no
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.address
	 * @return  the value of sys_user.address
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.address
	 * @param address  the value for sys_user.address
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.note
	 * @return  the value of sys_user.note
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.note
	 * @param note  the value for sys_user.note
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.version_id
	 * @return  the value of sys_user.version_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Long getVersionId() {
		return versionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.version_id
	 * @param versionId  the value for sys_user.version_id
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setVersionId(Long versionId) {
		this.versionId = versionId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.reccreator
	 * @return  the value of sys_user.reccreator
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getReccreator() {
		return reccreator;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.reccreator
	 * @param reccreator  the value for sys_user.reccreator
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setReccreator(String reccreator) {
		this.reccreator = reccreator;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.reccreate_time
	 * @return  the value of sys_user.reccreate_time
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Date getReccreateTime() {
		return reccreateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.reccreate_time
	 * @param reccreateTime  the value for sys_user.reccreate_time
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setReccreateTime(Date reccreateTime) {
		this.reccreateTime = reccreateTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.recrevisor
	 * @return  the value of sys_user.recrevisor
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getRecrevisor() {
		return recrevisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.recrevisor
	 * @param recrevisor  the value for sys_user.recrevisor
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setRecrevisor(String recrevisor) {
		this.recrevisor = recrevisor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.recrevise_time
	 * @return  the value of sys_user.recrevise_time
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public Date getRecreviseTime() {
		return recreviseTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.recrevise_time
	 * @param recreviseTime  the value for sys_user.recrevise_time
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setRecreviseTime(Date recreviseTime) {
		this.recreviseTime = recreviseTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column sys_user.archive_flag
	 * @return  the value of sys_user.archive_flag
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public String getArchiveFlag() {
		return archiveFlag;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column sys_user.archive_flag
	 * @param archiveFlag  the value for sys_user.archive_flag
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void setArchiveFlag(String archiveFlag) {
		this.archiveFlag = archiveFlag;
	}
}