package org.sunside.rycs.repository.dao.system;

import java.util.List;
import org.sunside.rycs.repository.model.system.SysDept;
import org.sunside.rycs.repository.model.system.SysDeptExample;

public interface SysDeptDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int countByExample(SysDeptExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByExample(SysDeptExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insert(SysDept record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insertSelective(SysDept record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    List selectByExample(SysDeptExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    SysDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExampleSelective(SysDept record, SysDeptExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExample(SysDept record, SysDeptExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKeySelective(SysDept record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_dept
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKey(SysDept record);
}