package org.sunside.rycs.repository.dao.system;

import java.util.List;
import org.sunside.rycs.repository.model.system.SysRoleRight;
import org.sunside.rycs.repository.model.system.SysRoleRightExample;

public interface SysRoleRightDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int countByExample(SysRoleRightExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByExample(SysRoleRightExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insert(SysRoleRight record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insertSelective(SysRoleRight record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    List selectByExample(SysRoleRightExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    SysRoleRight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExampleSelective(SysRoleRight record, SysRoleRightExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExample(SysRoleRight record, SysRoleRightExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKeySelective(SysRoleRight record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKey(SysRoleRight record);
}