package org.sunside.rycs.repository.dao.system;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.sunside.rycs.repository.model.system.SysRoleRight;
import org.sunside.rycs.repository.model.system.SysRoleRightExample;

public class SysRoleRightDAOImpl extends SqlMapClientDaoSupport implements SysRoleRightDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public SysRoleRightDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int countByExample(SysRoleRightExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sys_role_right.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByExample(SysRoleRightExample example) {
        int rows = getSqlMapClientTemplate().delete("sys_role_right.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        SysRoleRight key = new SysRoleRight();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("sys_role_right.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insert(SysRoleRight record) {
        getSqlMapClientTemplate().insert("sys_role_right.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insertSelective(SysRoleRight record) {
        getSqlMapClientTemplate().insert("sys_role_right.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public List selectByExample(SysRoleRightExample example) {
        List list = getSqlMapClientTemplate().queryForList("sys_role_right.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public SysRoleRight selectByPrimaryKey(Integer id) {
        SysRoleRight key = new SysRoleRight();
        key.setId(id);
        SysRoleRight record = (SysRoleRight) getSqlMapClientTemplate().queryForObject("sys_role_right.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExampleSelective(SysRoleRight record, SysRoleRightExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sys_role_right.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExample(SysRoleRight record, SysRoleRightExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sys_role_right.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKeySelective(SysRoleRight record) {
        int rows = getSqlMapClientTemplate().update("sys_role_right.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKey(SysRoleRight record) {
        int rows = getSqlMapClientTemplate().update("sys_role_right.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sys_role_right
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private static class UpdateByExampleParms extends SysRoleRightExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysRoleRightExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}