package org.sunside.rycs.repository.dao.cust;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.sunside.rycs.repository.model.cust.CusBankAccount;
import org.sunside.rycs.repository.model.cust.CusBankAccountExample;

public class CusBankAccountDAOImpl extends SqlMapClientDaoSupport implements CusBankAccountDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusBankAccountDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int countByExample(CusBankAccountExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cus_bank_account.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByExample(CusBankAccountExample example) {
        int rows = getSqlMapClientTemplate().delete("cus_bank_account.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        CusBankAccount key = new CusBankAccount();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("cus_bank_account.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insert(CusBankAccount record) {
        getSqlMapClientTemplate().insert("cus_bank_account.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insertSelective(CusBankAccount record) {
        getSqlMapClientTemplate().insert("cus_bank_account.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public List selectByExample(CusBankAccountExample example) {
        List list = getSqlMapClientTemplate().queryForList("cus_bank_account.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusBankAccount selectByPrimaryKey(Integer id) {
        CusBankAccount key = new CusBankAccount();
        key.setId(id);
        CusBankAccount record = (CusBankAccount) getSqlMapClientTemplate().queryForObject("cus_bank_account.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExampleSelective(CusBankAccount record, CusBankAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cus_bank_account.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExample(CusBankAccount record, CusBankAccountExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cus_bank_account.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKeySelective(CusBankAccount record) {
        int rows = getSqlMapClientTemplate().update("cus_bank_account.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKey(CusBankAccount record) {
        int rows = getSqlMapClientTemplate().update("cus_bank_account.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private static class UpdateByExampleParms extends CusBankAccountExample {
        private Object record;

        public UpdateByExampleParms(Object record, CusBankAccountExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}