package org.sunside.rycs.repository.dao.cust;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.sunside.rycs.repository.model.cust.CusTax;
import org.sunside.rycs.repository.model.cust.CusTaxExample;

public class CusTaxDAOImpl extends SqlMapClientDaoSupport implements CusTaxDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusTaxDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int countByExample(CusTaxExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cus_tax.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByExample(CusTaxExample example) {
        int rows = getSqlMapClientTemplate().delete("cus_tax.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        CusTax key = new CusTax();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("cus_tax.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insert(CusTax record) {
        getSqlMapClientTemplate().insert("cus_tax.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insertSelective(CusTax record) {
        getSqlMapClientTemplate().insert("cus_tax.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public List selectByExample(CusTaxExample example) {
        List list = getSqlMapClientTemplate().queryForList("cus_tax.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusTax selectByPrimaryKey(Integer id) {
        CusTax key = new CusTax();
        key.setId(id);
        CusTax record = (CusTax) getSqlMapClientTemplate().queryForObject("cus_tax.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExampleSelective(CusTax record, CusTaxExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cus_tax.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExample(CusTax record, CusTaxExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cus_tax.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKeySelective(CusTax record) {
        int rows = getSqlMapClientTemplate().update("cus_tax.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKey(CusTax record) {
        int rows = getSqlMapClientTemplate().update("cus_tax.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cus_tax
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private static class UpdateByExampleParms extends CusTaxExample {
        private Object record;

        public UpdateByExampleParms(Object record, CusTaxExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}