package org.sunside.rycs.repository.model.cust;

public class CusContacter {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_contacter.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_contacter.cus_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer cusId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_contacter.contacter_type
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String contacterType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_contacter.contacter_name
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String contacterName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_contacter.contacter_tel
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String contacterTel;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_contacter.id
     *
     * @return the value of cus_contacter.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_contacter.id
     *
     * @param id the value for cus_contacter.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_contacter.cus_id
     *
     * @return the value of cus_contacter.cus_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_contacter.cus_id
     *
     * @param cusId the value for cus_contacter.cus_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_contacter.contacter_type
     *
     * @return the value of cus_contacter.contacter_type
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getContacterType() {
        return contacterType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_contacter.contacter_type
     *
     * @param contacterType the value for cus_contacter.contacter_type
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setContacterType(String contacterType) {
        this.contacterType = contacterType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_contacter.contacter_name
     *
     * @return the value of cus_contacter.contacter_name
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getContacterName() {
        return contacterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_contacter.contacter_name
     *
     * @param contacterName the value for cus_contacter.contacter_name
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setContacterName(String contacterName) {
        this.contacterName = contacterName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_contacter.contacter_tel
     *
     * @return the value of cus_contacter.contacter_tel
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getContacterTel() {
        return contacterTel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_contacter.contacter_tel
     *
     * @param contacterTel the value for cus_contacter.contacter_tel
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setContacterTel(String contacterTel) {
        this.contacterTel = contacterTel;
    }
}