package org.sunside.frame.ibatis.repository.dao;

import java.util.List;
import org.sunside.frame.ibatis.repository.model.SysUser;
import org.sunside.frame.ibatis.repository.model.SysUserExample;
import java.sql.SQLException;

public interface SysUserDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int countByExample(SysUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int deleteByExample(SysUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	void insert(SysUser record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	void insertSelective(SysUser record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	List selectByExample(SysUserExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	SysUser selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int updateByExampleSelective(SysUser record, SysUserExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int updateByExample(SysUser record, SysUserExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int updateByPrimaryKeySelective(SysUser record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	int updateByPrimaryKey(SysUser record) throws SQLException;
}