package org.sunside.rycs.repository.dao.cust;

import java.util.List;
import org.sunside.rycs.repository.model.cust.CusBankAccount;
import org.sunside.rycs.repository.model.cust.CusBankAccountExample;

public interface CusBankAccountDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int countByExample(CusBankAccountExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByExample(CusBankAccountExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insert(CusBankAccount record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insertSelective(CusBankAccount record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    List selectByExample(CusBankAccountExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    CusBankAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExampleSelective(CusBankAccount record, CusBankAccountExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExample(CusBankAccount record, CusBankAccountExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKeySelective(CusBankAccount record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_bank_account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKey(CusBankAccount record);
}