package org.sunside.rycs.repository.dao.cust;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.sunside.rycs.repository.model.cust.CusFee;
import org.sunside.rycs.repository.model.cust.CusFeeExample;

public class CusFeeDAOImpl extends SqlMapClientDaoSupport implements CusFeeDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusFeeDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int countByExample(CusFeeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("cus_fee.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByExample(CusFeeExample example) {
        int rows = getSqlMapClientTemplate().delete("cus_fee.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int deleteByPrimaryKey(Integer id) {
        CusFee key = new CusFee();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("cus_fee.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insert(CusFee record) {
        getSqlMapClientTemplate().insert("cus_fee.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void insertSelective(CusFee record) {
        getSqlMapClientTemplate().insert("cus_fee.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public List selectByExample(CusFeeExample example) {
        List list = getSqlMapClientTemplate().queryForList("cus_fee.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusFee selectByPrimaryKey(Integer id) {
        CusFee key = new CusFee();
        key.setId(id);
        CusFee record = (CusFee) getSqlMapClientTemplate().queryForObject("cus_fee.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExampleSelective(CusFee record, CusFeeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cus_fee.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByExample(CusFee record, CusFeeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("cus_fee.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKeySelective(CusFee record) {
        int rows = getSqlMapClientTemplate().update("cus_fee.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public int updateByPrimaryKey(CusFee record) {
        int rows = getSqlMapClientTemplate().update("cus_fee.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cus_fee
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private static class UpdateByExampleParms extends CusFeeExample {
        private Object record;

        public UpdateByExampleParms(Object record, CusFeeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}