package org.sunside.rycs.repository.dao.cust;

import java.util.List;
import org.sunside.rycs.repository.model.cust.CusInfo;
import org.sunside.rycs.repository.model.cust.CusInfoExample;

public interface CusInfoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int countByExample(CusInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByExample(CusInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insert(CusInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insertSelective(CusInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    List selectByExample(CusInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    CusInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExampleSelective(CusInfo record, CusInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExample(CusInfo record, CusInfoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKeySelective(CusInfo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKey(CusInfo record);
}