package org.sunside.rycs.repository.dao.cust;

import java.util.List;
import org.sunside.rycs.repository.model.cust.CusLicense;
import org.sunside.rycs.repository.model.cust.CusLicenseExample;

public interface CusLicenseDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int countByExample(CusLicenseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByExample(CusLicenseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insert(CusLicense record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    void insertSelective(CusLicense record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    List selectByExample(CusLicenseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    CusLicense selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExampleSelective(CusLicense record, CusLicenseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByExample(CusLicense record, CusLicenseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKeySelective(CusLicense record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_license
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    int updateByPrimaryKey(CusLicense record);
}