package org.sunside.frame.ibatis.repository.dao;

import java.util.List;

import org.sunside.frame.ibatis.repository.model.SysUser;
import org.sunside.frame.ibatis.repository.model.SysUserExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class SysUserDAOImpl implements SysUserDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public SysUserDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int countByExample(SysUserExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"sys_user.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int deleteByExample(SysUserExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"sys_user.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		SysUser key = new SysUser();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"sys_user.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void insert(SysUser record) throws SQLException {
		sqlMapClient.insert("sys_user.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public void insertSelective(SysUser record) throws SQLException {
		sqlMapClient.insert("sys_user.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public List selectByExample(SysUserExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"sys_user.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public SysUser selectByPrimaryKey(Integer id) throws SQLException {
		SysUser key = new SysUser();
		key.setId(id);
		SysUser record = (SysUser) sqlMapClient.queryForObject(
				"sys_user.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int updateByExampleSelective(SysUser record, SysUserExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"sys_user.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int updateByExample(SysUser record, SysUserExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"sys_user.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int updateByPrimaryKeySelective(SysUser record) throws SQLException {
		int rows = sqlMapClient.update(
				"sys_user.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	public int updateByPrimaryKey(SysUser record) throws SQLException {
		int rows = sqlMapClient.update(
				"sys_user.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table sys_user
	 * @ibatorgenerated  Mon Oct 22 00:29:10 CST 2012
	 */
	private static class UpdateByExampleParms extends SysUserExample {
		private Object record;

		public UpdateByExampleParms(Object record, SysUserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}