package org.sunside.rycs.repository.model.system;

public class SysDataRight {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_data_right.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_data_right.sys_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Long sysId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_data_right.sys_user_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Long sysUserId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_data_right.id
     *
     * @return the value of sys_data_right.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_data_right.id
     *
     * @param id the value for sys_data_right.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_data_right.sys_id
     *
     * @return the value of sys_data_right.sys_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Long getSysId() {
        return sysId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_data_right.sys_id
     *
     * @param sysId the value for sys_data_right.sys_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_data_right.sys_user_id
     *
     * @return the value of sys_data_right.sys_user_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_data_right.sys_user_id
     *
     * @param sysUserId the value for sys_data_right.sys_user_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }
}