package org.sunside.rycs.repository.model.system;

public class SysRoleRight {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_role_right.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_role_right.role_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Long roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_role_right.right_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Long rightId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_role_right.id
     *
     * @return the value of sys_role_right.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_role_right.id
     *
     * @param id the value for sys_role_right.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_role_right.role_id
     *
     * @return the value of sys_role_right.role_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_role_right.role_id
     *
     * @param roleId the value for sys_role_right.role_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_role_right.right_id
     *
     * @return the value of sys_role_right.right_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_role_right.right_id
     *
     * @param rightId the value for sys_role_right.right_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }
}