package org.sunside.rycs.repository.model.cust;

public class CusBankAccount {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_bank_account.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_bank_account.cus_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer cusId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_bank_account.name
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_bank_account.account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String account;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_bank_account.type
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column cus_bank_account.remark
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private String remark;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_bank_account.id
     *
     * @return the value of cus_bank_account.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_bank_account.id
     *
     * @param id the value for cus_bank_account.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_bank_account.cus_id
     *
     * @return the value of cus_bank_account.cus_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_bank_account.cus_id
     *
     * @param cusId the value for cus_bank_account.cus_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_bank_account.name
     *
     * @return the value of cus_bank_account.name
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_bank_account.name
     *
     * @param name the value for cus_bank_account.name
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_bank_account.account
     *
     * @return the value of cus_bank_account.account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_bank_account.account
     *
     * @param account the value for cus_bank_account.account
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_bank_account.type
     *
     * @return the value of cus_bank_account.type
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_bank_account.type
     *
     * @param type the value for cus_bank_account.type
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column cus_bank_account.remark
     *
     * @return the value of cus_bank_account.remark
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column cus_bank_account.remark
     *
     * @param remark the value for cus_bank_account.remark
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}