package org.sunside.rycs.repository.model.cust;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class CusInfoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public CusInfoExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected CusInfoExample(CusInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table cus_info
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List values) {
            addCriterion("user_id in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List values) {
            addCriterion("user_id not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return this;
        }

        public Criteria andShortNameIsNull() {
            addCriterion("short_name is null");
            return this;
        }

        public Criteria andShortNameIsNotNull() {
            addCriterion("short_name is not null");
            return this;
        }

        public Criteria andShortNameEqualTo(String value) {
            addCriterion("short_name =", value, "shortName");
            return this;
        }

        public Criteria andShortNameNotEqualTo(String value) {
            addCriterion("short_name <>", value, "shortName");
            return this;
        }

        public Criteria andShortNameGreaterThan(String value) {
            addCriterion("short_name >", value, "shortName");
            return this;
        }

        public Criteria andShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("short_name >=", value, "shortName");
            return this;
        }

        public Criteria andShortNameLessThan(String value) {
            addCriterion("short_name <", value, "shortName");
            return this;
        }

        public Criteria andShortNameLessThanOrEqualTo(String value) {
            addCriterion("short_name <=", value, "shortName");
            return this;
        }

        public Criteria andShortNameLike(String value) {
            addCriterion("short_name like", value, "shortName");
            return this;
        }

        public Criteria andShortNameNotLike(String value) {
            addCriterion("short_name not like", value, "shortName");
            return this;
        }

        public Criteria andShortNameIn(List values) {
            addCriterion("short_name in", values, "shortName");
            return this;
        }

        public Criteria andShortNameNotIn(List values) {
            addCriterion("short_name not in", values, "shortName");
            return this;
        }

        public Criteria andShortNameBetween(String value1, String value2) {
            addCriterion("short_name between", value1, value2, "shortName");
            return this;
        }

        public Criteria andShortNameNotBetween(String value1, String value2) {
            addCriterion("short_name not between", value1, value2, "shortName");
            return this;
        }

        public Criteria andEstablishedDateIsNull() {
            addCriterion("established_date is null");
            return this;
        }

        public Criteria andEstablishedDateIsNotNull() {
            addCriterion("established_date is not null");
            return this;
        }

        public Criteria andEstablishedDateEqualTo(Date value) {
            addCriterionForJDBCDate("established_date =", value, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("established_date <>", value, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("established_date >", value, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("established_date >=", value, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateLessThan(Date value) {
            addCriterionForJDBCDate("established_date <", value, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("established_date <=", value, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateIn(List values) {
            addCriterionForJDBCDate("established_date in", values, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateNotIn(List values) {
            addCriterionForJDBCDate("established_date not in", values, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("established_date between", value1, value2, "establishedDate");
            return this;
        }

        public Criteria andEstablishedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("established_date not between", value1, value2, "establishedDate");
            return this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return this;
        }

        public Criteria andTypeIn(List values) {
            addCriterion("type in", values, "type");
            return this;
        }

        public Criteria andTypeNotIn(List values) {
            addCriterion("type not in", values, "type");
            return this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return this;
        }

        public Criteria andRegisteredCapitalIsNull() {
            addCriterion("registered_capital is null");
            return this;
        }

        public Criteria andRegisteredCapitalIsNotNull() {
            addCriterion("registered_capital is not null");
            return this;
        }

        public Criteria andRegisteredCapitalEqualTo(Double value) {
            addCriterion("registered_capital =", value, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalNotEqualTo(Double value) {
            addCriterion("registered_capital <>", value, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalGreaterThan(Double value) {
            addCriterion("registered_capital >", value, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalGreaterThanOrEqualTo(Double value) {
            addCriterion("registered_capital >=", value, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalLessThan(Double value) {
            addCriterion("registered_capital <", value, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalLessThanOrEqualTo(Double value) {
            addCriterion("registered_capital <=", value, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalIn(List values) {
            addCriterion("registered_capital in", values, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalNotIn(List values) {
            addCriterion("registered_capital not in", values, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalBetween(Double value1, Double value2) {
            addCriterion("registered_capital between", value1, value2, "registeredCapital");
            return this;
        }

        public Criteria andRegisteredCapitalNotBetween(Double value1, Double value2) {
            addCriterion("registered_capital not between", value1, value2, "registeredCapital");
            return this;
        }

        public Criteria andRealCapitalIsNull() {
            addCriterion("real_capital is null");
            return this;
        }

        public Criteria andRealCapitalIsNotNull() {
            addCriterion("real_capital is not null");
            return this;
        }

        public Criteria andRealCapitalEqualTo(Double value) {
            addCriterion("real_capital =", value, "realCapital");
            return this;
        }

        public Criteria andRealCapitalNotEqualTo(Double value) {
            addCriterion("real_capital <>", value, "realCapital");
            return this;
        }

        public Criteria andRealCapitalGreaterThan(Double value) {
            addCriterion("real_capital >", value, "realCapital");
            return this;
        }

        public Criteria andRealCapitalGreaterThanOrEqualTo(Double value) {
            addCriterion("real_capital >=", value, "realCapital");
            return this;
        }

        public Criteria andRealCapitalLessThan(Double value) {
            addCriterion("real_capital <", value, "realCapital");
            return this;
        }

        public Criteria andRealCapitalLessThanOrEqualTo(Double value) {
            addCriterion("real_capital <=", value, "realCapital");
            return this;
        }

        public Criteria andRealCapitalIn(List values) {
            addCriterion("real_capital in", values, "realCapital");
            return this;
        }

        public Criteria andRealCapitalNotIn(List values) {
            addCriterion("real_capital not in", values, "realCapital");
            return this;
        }

        public Criteria andRealCapitalBetween(Double value1, Double value2) {
            addCriterion("real_capital between", value1, value2, "realCapital");
            return this;
        }

        public Criteria andRealCapitalNotBetween(Double value1, Double value2) {
            addCriterion("real_capital not between", value1, value2, "realCapital");
            return this;
        }

        public Criteria andInsurcodeIsNull() {
            addCriterion("insurcode is null");
            return this;
        }

        public Criteria andInsurcodeIsNotNull() {
            addCriterion("insurcode is not null");
            return this;
        }

        public Criteria andInsurcodeEqualTo(String value) {
            addCriterion("insurcode =", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeNotEqualTo(String value) {
            addCriterion("insurcode <>", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeGreaterThan(String value) {
            addCriterion("insurcode >", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeGreaterThanOrEqualTo(String value) {
            addCriterion("insurcode >=", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeLessThan(String value) {
            addCriterion("insurcode <", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeLessThanOrEqualTo(String value) {
            addCriterion("insurcode <=", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeLike(String value) {
            addCriterion("insurcode like", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeNotLike(String value) {
            addCriterion("insurcode not like", value, "insurcode");
            return this;
        }

        public Criteria andInsurcodeIn(List values) {
            addCriterion("insurcode in", values, "insurcode");
            return this;
        }

        public Criteria andInsurcodeNotIn(List values) {
            addCriterion("insurcode not in", values, "insurcode");
            return this;
        }

        public Criteria andInsurcodeBetween(String value1, String value2) {
            addCriterion("insurcode between", value1, value2, "insurcode");
            return this;
        }

        public Criteria andInsurcodeNotBetween(String value1, String value2) {
            addCriterion("insurcode not between", value1, value2, "insurcode");
            return this;
        }

        public Criteria andLegalNameIsNull() {
            addCriterion("legal_name is null");
            return this;
        }

        public Criteria andLegalNameIsNotNull() {
            addCriterion("legal_name is not null");
            return this;
        }

        public Criteria andLegalNameEqualTo(String value) {
            addCriterion("legal_name =", value, "legalName");
            return this;
        }

        public Criteria andLegalNameNotEqualTo(String value) {
            addCriterion("legal_name <>", value, "legalName");
            return this;
        }

        public Criteria andLegalNameGreaterThan(String value) {
            addCriterion("legal_name >", value, "legalName");
            return this;
        }

        public Criteria andLegalNameGreaterThanOrEqualTo(String value) {
            addCriterion("legal_name >=", value, "legalName");
            return this;
        }

        public Criteria andLegalNameLessThan(String value) {
            addCriterion("legal_name <", value, "legalName");
            return this;
        }

        public Criteria andLegalNameLessThanOrEqualTo(String value) {
            addCriterion("legal_name <=", value, "legalName");
            return this;
        }

        public Criteria andLegalNameLike(String value) {
            addCriterion("legal_name like", value, "legalName");
            return this;
        }

        public Criteria andLegalNameNotLike(String value) {
            addCriterion("legal_name not like", value, "legalName");
            return this;
        }

        public Criteria andLegalNameIn(List values) {
            addCriterion("legal_name in", values, "legalName");
            return this;
        }

        public Criteria andLegalNameNotIn(List values) {
            addCriterion("legal_name not in", values, "legalName");
            return this;
        }

        public Criteria andLegalNameBetween(String value1, String value2) {
            addCriterion("legal_name between", value1, value2, "legalName");
            return this;
        }

        public Criteria andLegalNameNotBetween(String value1, String value2) {
            addCriterion("legal_name not between", value1, value2, "legalName");
            return this;
        }

        public Criteria andLegalPhoneIsNull() {
            addCriterion("legal_phone is null");
            return this;
        }

        public Criteria andLegalPhoneIsNotNull() {
            addCriterion("legal_phone is not null");
            return this;
        }

        public Criteria andLegalPhoneEqualTo(String value) {
            addCriterion("legal_phone =", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneNotEqualTo(String value) {
            addCriterion("legal_phone <>", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneGreaterThan(String value) {
            addCriterion("legal_phone >", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("legal_phone >=", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneLessThan(String value) {
            addCriterion("legal_phone <", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneLessThanOrEqualTo(String value) {
            addCriterion("legal_phone <=", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneLike(String value) {
            addCriterion("legal_phone like", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneNotLike(String value) {
            addCriterion("legal_phone not like", value, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneIn(List values) {
            addCriterion("legal_phone in", values, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneNotIn(List values) {
            addCriterion("legal_phone not in", values, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneBetween(String value1, String value2) {
            addCriterion("legal_phone between", value1, value2, "legalPhone");
            return this;
        }

        public Criteria andLegalPhoneNotBetween(String value1, String value2) {
            addCriterion("legal_phone not between", value1, value2, "legalPhone");
            return this;
        }

        public Criteria andLegalIdCardIsNull() {
            addCriterion("legal_id_card is null");
            return this;
        }

        public Criteria andLegalIdCardIsNotNull() {
            addCriterion("legal_id_card is not null");
            return this;
        }

        public Criteria andLegalIdCardEqualTo(String value) {
            addCriterion("legal_id_card =", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardNotEqualTo(String value) {
            addCriterion("legal_id_card <>", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardGreaterThan(String value) {
            addCriterion("legal_id_card >", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("legal_id_card >=", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardLessThan(String value) {
            addCriterion("legal_id_card <", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardLessThanOrEqualTo(String value) {
            addCriterion("legal_id_card <=", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardLike(String value) {
            addCriterion("legal_id_card like", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardNotLike(String value) {
            addCriterion("legal_id_card not like", value, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardIn(List values) {
            addCriterion("legal_id_card in", values, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardNotIn(List values) {
            addCriterion("legal_id_card not in", values, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardBetween(String value1, String value2) {
            addCriterion("legal_id_card between", value1, value2, "legalIdCard");
            return this;
        }

        public Criteria andLegalIdCardNotBetween(String value1, String value2) {
            addCriterion("legal_id_card not between", value1, value2, "legalIdCard");
            return this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("scope =", value, "scope");
            return this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("scope <>", value, "scope");
            return this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("scope >", value, "scope");
            return this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("scope >=", value, "scope");
            return this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("scope <", value, "scope");
            return this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("scope <=", value, "scope");
            return this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("scope like", value, "scope");
            return this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("scope not like", value, "scope");
            return this;
        }

        public Criteria andScopeIn(List values) {
            addCriterion("scope in", values, "scope");
            return this;
        }

        public Criteria andScopeNotIn(List values) {
            addCriterion("scope not in", values, "scope");
            return this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("scope between", value1, value2, "scope");
            return this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("end_date =", value, "endDate");
            return this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <>", value, "endDate");
            return this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("end_date >", value, "endDate");
            return this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date >=", value, "endDate");
            return this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterionForJDBCDate("end_date <", value, "endDate");
            return this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <=", value, "endDate");
            return this;
        }

        public Criteria andEndDateIn(List values) {
            addCriterionForJDBCDate("end_date in", values, "endDate");
            return this;
        }

        public Criteria andEndDateNotIn(List values) {
            addCriterionForJDBCDate("end_date not in", values, "endDate");
            return this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
            return this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
            return this;
        }

        public Criteria andRegisteredAddressIsNull() {
            addCriterion("registered_address is null");
            return this;
        }

        public Criteria andRegisteredAddressIsNotNull() {
            addCriterion("registered_address is not null");
            return this;
        }

        public Criteria andRegisteredAddressEqualTo(String value) {
            addCriterion("registered_address =", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressNotEqualTo(String value) {
            addCriterion("registered_address <>", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressGreaterThan(String value) {
            addCriterion("registered_address >", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressGreaterThanOrEqualTo(String value) {
            addCriterion("registered_address >=", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressLessThan(String value) {
            addCriterion("registered_address <", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressLessThanOrEqualTo(String value) {
            addCriterion("registered_address <=", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressLike(String value) {
            addCriterion("registered_address like", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressNotLike(String value) {
            addCriterion("registered_address not like", value, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressIn(List values) {
            addCriterion("registered_address in", values, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressNotIn(List values) {
            addCriterion("registered_address not in", values, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressBetween(String value1, String value2) {
            addCriterion("registered_address between", value1, value2, "registeredAddress");
            return this;
        }

        public Criteria andRegisteredAddressNotBetween(String value1, String value2) {
            addCriterion("registered_address not between", value1, value2, "registeredAddress");
            return this;
        }

        public Criteria andRealAddressIsNull() {
            addCriterion("real_address is null");
            return this;
        }

        public Criteria andRealAddressIsNotNull() {
            addCriterion("real_address is not null");
            return this;
        }

        public Criteria andRealAddressEqualTo(String value) {
            addCriterion("real_address =", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressNotEqualTo(String value) {
            addCriterion("real_address <>", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressGreaterThan(String value) {
            addCriterion("real_address >", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressGreaterThanOrEqualTo(String value) {
            addCriterion("real_address >=", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressLessThan(String value) {
            addCriterion("real_address <", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressLessThanOrEqualTo(String value) {
            addCriterion("real_address <=", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressLike(String value) {
            addCriterion("real_address like", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressNotLike(String value) {
            addCriterion("real_address not like", value, "realAddress");
            return this;
        }

        public Criteria andRealAddressIn(List values) {
            addCriterion("real_address in", values, "realAddress");
            return this;
        }

        public Criteria andRealAddressNotIn(List values) {
            addCriterion("real_address not in", values, "realAddress");
            return this;
        }

        public Criteria andRealAddressBetween(String value1, String value2) {
            addCriterion("real_address between", value1, value2, "realAddress");
            return this;
        }

        public Criteria andRealAddressNotBetween(String value1, String value2) {
            addCriterion("real_address not between", value1, value2, "realAddress");
            return this;
        }

        public Criteria andUpdUsrIdIsNull() {
            addCriterion("UPD_USR_ID is null");
            return this;
        }

        public Criteria andUpdUsrIdIsNotNull() {
            addCriterion("UPD_USR_ID is not null");
            return this;
        }

        public Criteria andUpdUsrIdEqualTo(Long value) {
            addCriterion("UPD_USR_ID =", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdNotEqualTo(Long value) {
            addCriterion("UPD_USR_ID <>", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdGreaterThan(Long value) {
            addCriterion("UPD_USR_ID >", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UPD_USR_ID >=", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdLessThan(Long value) {
            addCriterion("UPD_USR_ID <", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdLessThanOrEqualTo(Long value) {
            addCriterion("UPD_USR_ID <=", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdIn(List values) {
            addCriterion("UPD_USR_ID in", values, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdNotIn(List values) {
            addCriterion("UPD_USR_ID not in", values, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdBetween(Long value1, Long value2) {
            addCriterion("UPD_USR_ID between", value1, value2, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdNotBetween(Long value1, Long value2) {
            addCriterion("UPD_USR_ID not between", value1, value2, "updUsrId");
            return this;
        }

        public Criteria andUpdDtIsNull() {
            addCriterion("UPD_DT is null");
            return this;
        }

        public Criteria andUpdDtIsNotNull() {
            addCriterion("UPD_DT is not null");
            return this;
        }

        public Criteria andUpdDtEqualTo(Date value) {
            addCriterion("UPD_DT =", value, "updDt");
            return this;
        }

        public Criteria andUpdDtNotEqualTo(Date value) {
            addCriterion("UPD_DT <>", value, "updDt");
            return this;
        }

        public Criteria andUpdDtGreaterThan(Date value) {
            addCriterion("UPD_DT >", value, "updDt");
            return this;
        }

        public Criteria andUpdDtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DT >=", value, "updDt");
            return this;
        }

        public Criteria andUpdDtLessThan(Date value) {
            addCriterion("UPD_DT <", value, "updDt");
            return this;
        }

        public Criteria andUpdDtLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DT <=", value, "updDt");
            return this;
        }

        public Criteria andUpdDtIn(List values) {
            addCriterion("UPD_DT in", values, "updDt");
            return this;
        }

        public Criteria andUpdDtNotIn(List values) {
            addCriterion("UPD_DT not in", values, "updDt");
            return this;
        }

        public Criteria andUpdDtBetween(Date value1, Date value2) {
            addCriterion("UPD_DT between", value1, value2, "updDt");
            return this;
        }

        public Criteria andUpdDtNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DT not between", value1, value2, "updDt");
            return this;
        }

        public Criteria andCrtdUsrIdIsNull() {
            addCriterion("CRTD_USR_ID is null");
            return this;
        }

        public Criteria andCrtdUsrIdIsNotNull() {
            addCriterion("CRTD_USR_ID is not null");
            return this;
        }

        public Criteria andCrtdUsrIdEqualTo(Long value) {
            addCriterion("CRTD_USR_ID =", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdNotEqualTo(Long value) {
            addCriterion("CRTD_USR_ID <>", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdGreaterThan(Long value) {
            addCriterion("CRTD_USR_ID >", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CRTD_USR_ID >=", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdLessThan(Long value) {
            addCriterion("CRTD_USR_ID <", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdLessThanOrEqualTo(Long value) {
            addCriterion("CRTD_USR_ID <=", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdIn(List values) {
            addCriterion("CRTD_USR_ID in", values, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdNotIn(List values) {
            addCriterion("CRTD_USR_ID not in", values, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdBetween(Long value1, Long value2) {
            addCriterion("CRTD_USR_ID between", value1, value2, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdNotBetween(Long value1, Long value2) {
            addCriterion("CRTD_USR_ID not between", value1, value2, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdDtIsNull() {
            addCriterion("CRTD_DT is null");
            return this;
        }

        public Criteria andCrtdDtIsNotNull() {
            addCriterion("CRTD_DT is not null");
            return this;
        }

        public Criteria andCrtdDtEqualTo(Date value) {
            addCriterion("CRTD_DT =", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtNotEqualTo(Date value) {
            addCriterion("CRTD_DT <>", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtGreaterThan(Date value) {
            addCriterion("CRTD_DT >", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtGreaterThanOrEqualTo(Date value) {
            addCriterion("CRTD_DT >=", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtLessThan(Date value) {
            addCriterion("CRTD_DT <", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtLessThanOrEqualTo(Date value) {
            addCriterion("CRTD_DT <=", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtIn(List values) {
            addCriterion("CRTD_DT in", values, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtNotIn(List values) {
            addCriterion("CRTD_DT not in", values, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtBetween(Date value1, Date value2) {
            addCriterion("CRTD_DT between", value1, value2, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtNotBetween(Date value1, Date value2) {
            addCriterion("CRTD_DT not between", value1, value2, "crtdDt");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("remark in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("remark not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return this;
        }
    }
}