package org.sunside.rycs.repository.model.system;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SysUserExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public SysUserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected SysUserExample(SysUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table sys_user
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andPostIdIsNull() {
            addCriterion("post_id is null");
            return this;
        }

        public Criteria andPostIdIsNotNull() {
            addCriterion("post_id is not null");
            return this;
        }

        public Criteria andPostIdEqualTo(Long value) {
            addCriterion("post_id =", value, "postId");
            return this;
        }

        public Criteria andPostIdNotEqualTo(Long value) {
            addCriterion("post_id <>", value, "postId");
            return this;
        }

        public Criteria andPostIdGreaterThan(Long value) {
            addCriterion("post_id >", value, "postId");
            return this;
        }

        public Criteria andPostIdGreaterThanOrEqualTo(Long value) {
            addCriterion("post_id >=", value, "postId");
            return this;
        }

        public Criteria andPostIdLessThan(Long value) {
            addCriterion("post_id <", value, "postId");
            return this;
        }

        public Criteria andPostIdLessThanOrEqualTo(Long value) {
            addCriterion("post_id <=", value, "postId");
            return this;
        }

        public Criteria andPostIdIn(List values) {
            addCriterion("post_id in", values, "postId");
            return this;
        }

        public Criteria andPostIdNotIn(List values) {
            addCriterion("post_id not in", values, "postId");
            return this;
        }

        public Criteria andPostIdBetween(Long value1, Long value2) {
            addCriterion("post_id between", value1, value2, "postId");
            return this;
        }

        public Criteria andPostIdNotBetween(Long value1, Long value2) {
            addCriterion("post_id not between", value1, value2, "postId");
            return this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return this;
        }

        public Criteria andDeptIdEqualTo(Long value) {
            addCriterion("dept_id =", value, "deptId");
            return this;
        }

        public Criteria andDeptIdNotEqualTo(Long value) {
            addCriterion("dept_id <>", value, "deptId");
            return this;
        }

        public Criteria andDeptIdGreaterThan(Long value) {
            addCriterion("dept_id >", value, "deptId");
            return this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("dept_id >=", value, "deptId");
            return this;
        }

        public Criteria andDeptIdLessThan(Long value) {
            addCriterion("dept_id <", value, "deptId");
            return this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Long value) {
            addCriterion("dept_id <=", value, "deptId");
            return this;
        }

        public Criteria andDeptIdIn(List values) {
            addCriterion("dept_id in", values, "deptId");
            return this;
        }

        public Criteria andDeptIdNotIn(List values) {
            addCriterion("dept_id not in", values, "deptId");
            return this;
        }

        public Criteria andDeptIdBetween(Long value1, Long value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return this;
        }

        public Criteria andDeptIdNotBetween(Long value1, Long value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List values) {
            addCriterion("name in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List values) {
            addCriterion("name not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List values) {
            addCriterion("password in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List values) {
            addCriterion("password not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return this;
        }

        public Criteria andChinaNameIsNull() {
            addCriterion("china_name is null");
            return this;
        }

        public Criteria andChinaNameIsNotNull() {
            addCriterion("china_name is not null");
            return this;
        }

        public Criteria andChinaNameEqualTo(String value) {
            addCriterion("china_name =", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameNotEqualTo(String value) {
            addCriterion("china_name <>", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameGreaterThan(String value) {
            addCriterion("china_name >", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameGreaterThanOrEqualTo(String value) {
            addCriterion("china_name >=", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameLessThan(String value) {
            addCriterion("china_name <", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameLessThanOrEqualTo(String value) {
            addCriterion("china_name <=", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameLike(String value) {
            addCriterion("china_name like", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameNotLike(String value) {
            addCriterion("china_name not like", value, "chinaName");
            return this;
        }

        public Criteria andChinaNameIn(List values) {
            addCriterion("china_name in", values, "chinaName");
            return this;
        }

        public Criteria andChinaNameNotIn(List values) {
            addCriterion("china_name not in", values, "chinaName");
            return this;
        }

        public Criteria andChinaNameBetween(String value1, String value2) {
            addCriterion("china_name between", value1, value2, "chinaName");
            return this;
        }

        public Criteria andChinaNameNotBetween(String value1, String value2) {
            addCriterion("china_name not between", value1, value2, "chinaName");
            return this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return this;
        }

        public Criteria andAgeEqualTo(Short value) {
            addCriterion("age =", value, "age");
            return this;
        }

        public Criteria andAgeNotEqualTo(Short value) {
            addCriterion("age <>", value, "age");
            return this;
        }

        public Criteria andAgeGreaterThan(Short value) {
            addCriterion("age >", value, "age");
            return this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Short value) {
            addCriterion("age >=", value, "age");
            return this;
        }

        public Criteria andAgeLessThan(Short value) {
            addCriterion("age <", value, "age");
            return this;
        }

        public Criteria andAgeLessThanOrEqualTo(Short value) {
            addCriterion("age <=", value, "age");
            return this;
        }

        public Criteria andAgeIn(List values) {
            addCriterion("age in", values, "age");
            return this;
        }

        public Criteria andAgeNotIn(List values) {
            addCriterion("age not in", values, "age");
            return this;
        }

        public Criteria andAgeBetween(Short value1, Short value2) {
            addCriterion("age between", value1, value2, "age");
            return this;
        }

        public Criteria andAgeNotBetween(Short value1, Short value2) {
            addCriterion("age not between", value1, value2, "age");
            return this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return this;
        }

        public Criteria andSexIn(List values) {
            addCriterion("sex in", values, "sex");
            return this;
        }

        public Criteria andSexNotIn(List values) {
            addCriterion("sex not in", values, "sex");
            return this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return this;
        }

        public Criteria andPhoneIn(List values) {
            addCriterion("phone in", values, "phone");
            return this;
        }

        public Criteria andPhoneNotIn(List values) {
            addCriterion("phone not in", values, "phone");
            return this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return this;
        }

        public Criteria andAddressIn(List values) {
            addCriterion("address in", values, "address");
            return this;
        }

        public Criteria andAddressNotIn(List values) {
            addCriterion("address not in", values, "address");
            return this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("last_login_time is null");
            return this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("last_login_time is not null");
            return this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("last_login_time =", value, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("last_login_time <>", value, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("last_login_time >", value, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_time >=", value, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("last_login_time <", value, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_time <=", value, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeIn(List values) {
            addCriterion("last_login_time in", values, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeNotIn(List values) {
            addCriterion("last_login_time not in", values, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_time between", value1, value2, "lastLoginTime");
            return this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
            return this;
        }

        public Criteria andUpdUsrIdIsNull() {
            addCriterion("UPD_USR_ID is null");
            return this;
        }

        public Criteria andUpdUsrIdIsNotNull() {
            addCriterion("UPD_USR_ID is not null");
            return this;
        }

        public Criteria andUpdUsrIdEqualTo(Long value) {
            addCriterion("UPD_USR_ID =", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdNotEqualTo(Long value) {
            addCriterion("UPD_USR_ID <>", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdGreaterThan(Long value) {
            addCriterion("UPD_USR_ID >", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("UPD_USR_ID >=", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdLessThan(Long value) {
            addCriterion("UPD_USR_ID <", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdLessThanOrEqualTo(Long value) {
            addCriterion("UPD_USR_ID <=", value, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdIn(List values) {
            addCriterion("UPD_USR_ID in", values, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdNotIn(List values) {
            addCriterion("UPD_USR_ID not in", values, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdBetween(Long value1, Long value2) {
            addCriterion("UPD_USR_ID between", value1, value2, "updUsrId");
            return this;
        }

        public Criteria andUpdUsrIdNotBetween(Long value1, Long value2) {
            addCriterion("UPD_USR_ID not between", value1, value2, "updUsrId");
            return this;
        }

        public Criteria andUpdDtIsNull() {
            addCriterion("UPD_DT is null");
            return this;
        }

        public Criteria andUpdDtIsNotNull() {
            addCriterion("UPD_DT is not null");
            return this;
        }

        public Criteria andUpdDtEqualTo(Date value) {
            addCriterion("UPD_DT =", value, "updDt");
            return this;
        }

        public Criteria andUpdDtNotEqualTo(Date value) {
            addCriterion("UPD_DT <>", value, "updDt");
            return this;
        }

        public Criteria andUpdDtGreaterThan(Date value) {
            addCriterion("UPD_DT >", value, "updDt");
            return this;
        }

        public Criteria andUpdDtGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DT >=", value, "updDt");
            return this;
        }

        public Criteria andUpdDtLessThan(Date value) {
            addCriterion("UPD_DT <", value, "updDt");
            return this;
        }

        public Criteria andUpdDtLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DT <=", value, "updDt");
            return this;
        }

        public Criteria andUpdDtIn(List values) {
            addCriterion("UPD_DT in", values, "updDt");
            return this;
        }

        public Criteria andUpdDtNotIn(List values) {
            addCriterion("UPD_DT not in", values, "updDt");
            return this;
        }

        public Criteria andUpdDtBetween(Date value1, Date value2) {
            addCriterion("UPD_DT between", value1, value2, "updDt");
            return this;
        }

        public Criteria andUpdDtNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DT not between", value1, value2, "updDt");
            return this;
        }

        public Criteria andCrtdUsrIdIsNull() {
            addCriterion("CRTD_USR_ID is null");
            return this;
        }

        public Criteria andCrtdUsrIdIsNotNull() {
            addCriterion("CRTD_USR_ID is not null");
            return this;
        }

        public Criteria andCrtdUsrIdEqualTo(Long value) {
            addCriterion("CRTD_USR_ID =", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdNotEqualTo(Long value) {
            addCriterion("CRTD_USR_ID <>", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdGreaterThan(Long value) {
            addCriterion("CRTD_USR_ID >", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CRTD_USR_ID >=", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdLessThan(Long value) {
            addCriterion("CRTD_USR_ID <", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdLessThanOrEqualTo(Long value) {
            addCriterion("CRTD_USR_ID <=", value, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdIn(List values) {
            addCriterion("CRTD_USR_ID in", values, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdNotIn(List values) {
            addCriterion("CRTD_USR_ID not in", values, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdBetween(Long value1, Long value2) {
            addCriterion("CRTD_USR_ID between", value1, value2, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdUsrIdNotBetween(Long value1, Long value2) {
            addCriterion("CRTD_USR_ID not between", value1, value2, "crtdUsrId");
            return this;
        }

        public Criteria andCrtdDtIsNull() {
            addCriterion("CRTD_DT is null");
            return this;
        }

        public Criteria andCrtdDtIsNotNull() {
            addCriterion("CRTD_DT is not null");
            return this;
        }

        public Criteria andCrtdDtEqualTo(Date value) {
            addCriterion("CRTD_DT =", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtNotEqualTo(Date value) {
            addCriterion("CRTD_DT <>", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtGreaterThan(Date value) {
            addCriterion("CRTD_DT >", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtGreaterThanOrEqualTo(Date value) {
            addCriterion("CRTD_DT >=", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtLessThan(Date value) {
            addCriterion("CRTD_DT <", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtLessThanOrEqualTo(Date value) {
            addCriterion("CRTD_DT <=", value, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtIn(List values) {
            addCriterion("CRTD_DT in", values, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtNotIn(List values) {
            addCriterion("CRTD_DT not in", values, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtBetween(Date value1, Date value2) {
            addCriterion("CRTD_DT between", value1, value2, "crtdDt");
            return this;
        }

        public Criteria andCrtdDtNotBetween(Date value1, Date value2) {
            addCriterion("CRTD_DT not between", value1, value2, "crtdDt");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("remark in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("remark not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return this;
        }
    }
}