package org.sunside.rycs.repository.model.system;

public class SysUserRole {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Long roleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column sys_user_role.user_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    private Long userId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_user_role.id
     *
     * @return the value of sys_user_role.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_user_role.id
     *
     * @param id the value for sys_user_role.id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_user_role.role_id
     *
     * @return the value of sys_user_role.role_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_user_role.role_id
     *
     * @param roleId the value for sys_user_role.role_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column sys_user_role.user_id
     *
     * @return the value of sys_user_role.user_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column sys_user_role.user_id
     *
     * @param userId the value for sys_user_role.user_id
     *
     * @ibatorgenerated Thu Sep 20 01:29:51 CST 2012
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}